parameters:
    im0rtality_task_scheduler.mongo.config:
        database:   tasks
        collection: tasks

services:
    im0rtality_task_scheduler.mongo_client:
        class: MongoClient

    im0rtality_task_scheduler.mongo_collection_factory:
        class: Im0rtality\TaskSchedulerBundle\Backend\MongoDB\MongoCollectionFactory
        calls:
            - [setClient, [@im0rtality_task_scheduler.mongo_client]]
            - [setConfig, [%im0rtality_task_scheduler.mongo.config%]]

    im0rtality_task_scheduler.mongo_collection:
        class: MongoCollection
        factory_service: im0rtality_task_scheduler.mongo_collection_factory
        factory_method: create

    im0rtality_task_scheduler.backend.mongo:
        class: Im0rtality\TaskSchedulerBundle\Backend\MongoDB\MongoDbBackend
        calls:
            - [setMongoCollection, [@im0rtality_task_scheduler.mongo_collection]]

    im0rtality_task_scheduler.scheduler:
        class: Im0rtality\TaskSchedulerBundle\Scheduler
        calls:
            - [setBackend, [@im0rtality_task_scheduler.backend.mongo]]
            - [setLogger, [@logger]]

    task_scheduler:
        alias: im0rtality_task_scheduler.scheduler
