parameters:
#    im0rtality_monitoring.example.class: Im0rtality\MonitoringBundle\Example

services:
#    im0rtality_monitoring.example:
#        class: %im0rtality_monitoring.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
